<?php

/**
* @file
* The VisualScience Module, from QScience.
*
* It allows you to sort, contact and more generally visualize scientific data about you users.
*/

//Tools pre-made by Vahe
require_once 'includes/visualscience.settings.inc';
require_once 'includes/visualscience.utils.inc';

//Classes for each functionality
require_once 'includes/visualscience.searchtable.class.php';
include_once 'includes/visualscience.message.class.php';
include_once 'includes/visualscience.upload.class.php';
include_once 'includes/visualscience.config.class.php';

define('VISUALSCIENCE_NUSER_LOADED', 1000);

/**
 * Implementation of hook_menu().
 */
function visualscience_menu() {

  $items['visualscience'] = array(
    'title' => 'Visual Science',
    'description' => 'Visual Science description',
    'page callback' => 'visualscience_page',
    'page arguments' => array(true),
    'access callback' => TRUE,
    'weight' => 30,
    );

  $items['visualscience/users'] = array(
    'title' => 'VisualScience Users Access',
    'description' => 'Get Users of VisualScience',
    'page callback' => 'visualscience_users',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    );

  // $items['visualscience/upload'] = array(
  //   'title' => 'VisualScience Upload',
  //   'description' => 'Upload a file in VisualScience',
  //   'page callback' => 'visualscience_upload_form',
  //   'access arguments' => array('access visualscience'),
  //   'type' => MENU_CALLBACK,
  //   );
  $items['visualscience/upload'] = array(
    'title' => 'VisualScience Upload',
    'description' => 'Upload a file in VisualScience',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('visualscience_upload_form'),
    'access arguments' => array('access visualscience'),
    'type' => MENU_CALLBACK,
    );

  $items['visualscience/file'] = array(
    'title' => 'VisualScience Attachment Access',
    'description' => 'Access a file uploaded from VisualScience',
    'page callback' => 'visualscience_get_file_with_id',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    );

  $items['visualscience/mail'] = array(
    'title' => 'VisualScience Mail Send',
    'description' => 'Send Mail from VisualScience',
    'page callback' => 'visualscience_send_message',
    'access arguments' => array('access visualscience'),
    'type' => MENU_CALLBACK,
    );

  $items['admin/config/media/visualscience'] = array(
    'title' => 'VisualScience Configuration',
    'description' => 'Configuration for the VisualScience module.',
    'page callback' => 'visualscience_config_page',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    );

  return $items;
}

// function visualscience_upload_form($form, &$form_state) {
//   // if (!isset($_FILES['visualscience_upload_file'])) {
//   //   $form = drupal_get_form('visualscience_get_upload_form');
//   //   print drupal_render($form);
//   // }
//   // else {
//   //   return visualscience_get_upload_form($form, $form_state);
//   // }
//   return drupal_get_form('visualscience_get_upload_form');
// } 
// 
function visualscience_upload_form($form, &$form_state) {
  $upload = new Upload;
  return $upload->visualscience_upload_form($form, $form_state);
}

function visualscience_get_file_with_id() {
  $upload = new Upload;
  return $upload->visualscience_get_file_with_id();
}

function visualscience_send_message() {
  $message = new Message;
  return $message->visualscience_send_message();
}

function visualscience_upload_submit($form, &$form_state) {
  $upload = new Upload;
  return $upload->visualscience_upload_submit($form, $form_state);
}

/**
 * Creates the visualscience page
 */
function visualscience_page($clear = TRUE) {
  $search = new Search;
  $search_to_perform = $search->getSavedSearch();
  $search->getClientSideFiles();
  $search_bar = $search->getHtmlSearchBar($search_to_perform);
  $search_table = $search->getHtmlsearchTable();
  $output = $search_bar . $search_table;
  return $output;
}

function visualscience_config_page($clear = TRUE) {
  $config = new Config;
  $output = '';
  if (isset($_POST['visualscience_config_form'])) {
    $config->saveSentValues();
    drupal_set_message(t('Configuration Saved !'), 'status');
  }
  $output .= $config->getHtmlConfigPage();
  return $output;
}

function visualscience_users() {
  $search = new Search;
  $from = intval($_GET['userId']);
  $database = $search->getUsersEntries($from, variable_get('visualscience_nuser_loaded', VISUALSCIENCE_NUSER_LOADED));
  echo $database;
}